project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "Estadística Descriptiva"
  site-url: "https://encuestas-sociales.netlify.app"
  #description: "Diseño, análisis, reporte y visualización de encuestas sociales"
  favicon: "/files/logo-removebg-preview.png"

  twitter-card:
    image: "/files/social-image-f22.png"
    card-style: summary_large_image
    creator: "@andreaslaffert"
    site: "@andreaslaffert"

  open-graph:
    image: "/files/logo.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#069393"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Contenidos"
        file: content/index.qmd
#      - text: "Assignments"
#        file: assignment/index.qmd
#      - text: "Examples"
#        file: example/index.qmd
      - trabajos.qmd
      - text: "Recursos"
        file: resource/index.qmd
      - text: "RStudio Cloud"
        href: "https://login.rstudio.cloud/login?redirect=%2F"

  sidebar:
    - title: "Contenidos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "1: Presentación"
              file: content/01-content.qmd
            - text: "2: Bases"
              file: content/02-content.qmd
            - text: "3: Medición"
              file: content/03-content.qmd
            - text: "4: Preguntas"
              file: content/04-content.qmd
            - text: "5: Cuestionario"
              file: content/05-content.qmd
            - text: "8: Flujo de trabajo"
              file: content/08-content.qmd
            - text: "9: Documentos dinámicos & RMarkdown"
              file: content/09-content.qmd
            - text: "10: Baterías e índices"
              file: content/10-content.qmd
            - text: "11: Análisis factorial"
              file: content/11-content.qmd
    - title: "Recursos"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Descripción"
          file: resource/index.qmd
        - text: "Bases de Datos"
          file: resource/01-resource.qmd
        - text: "Uso de R"
          file: resource/02-resource.qmd

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
