project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "img/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

bibliography: bib/references.bib
csl: bib/chicago-author-date.csl

website:
  title: "Program Evaluation"
  navbar:
    pinned: true
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Resources"
        file: resource/index.qmd
      - text: Slack
      - text: RStudio.cloud

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - content/01-content.qmd
            - content/02-content.qmd
            - content/03-content.qmd
            - content/04-content.qmd
            - content/05-content.qmd
            - content/06-content.qmd
            - content/07-content.qmd
            - content/08-content.qmd
            - content/09-content.qmd
            - content/10-content.qmd
            - content/11-content.qmd
            - content/12-content.qmd
            - content/13-content.qmd
            - content/14-content.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Problem sets"
          contents:
            - assignment/02-problem-set.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - example/rstudio-tidyverse.qmd

    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
